name : Bookstore CI/CD with Image Publishing
on:
  push:
    branches: [ master ]
    tags: ['v*']
  pull_request: 
    branches: [ master ]
  workflow_dispatch:
env:
  IMAGE_BACKEND: nileshk12/bookstore-backend
  IMAGE_FRONTEND: nileshk12/bookstore-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tag: nileshk12/bookstore-backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tag: nileshk12/bookstore-frontend:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/master'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Replace build with image name in docker compose
        run: |
         sed -i 's|build:\s*context: ./backend|image: ${{ env.IMAGE_BACKEND }}:latest|' docker-compose.yml
         sed -i 's|build:\s*context: ./frontend|image: ${{ env.IMAGE_FRONTEND }}:latest|' docker-compose.yml
         echo "updated docker compose"
         cat docker-compose.yml
      - name: Deploy with Docker compose
        run: |
          echo "Starting app using docker-compose"
          docker-compose down --volumes || true
          docker-compose up -d --force-recreate
          sleep 10
          docker-compose ps
      - name: show container logs
        run: docker-compose logs --tail=30
      
          




          
